# Generated by Django 6.0.1 on 2026-02-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('ordid', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('orddate', models.DateField()),
                ('deliveryaddress', models.CharField()),
                ('itemname', models.CharField()),
                ('unitprice', models.FloatField()),
                ('ordqt', models.IntegerField()),
                ('totalamount', models.FloatField()),
            ],
        ),
    ]
